language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

#notifications
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always