language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
#travis can is not able to install schema
  - pip install schema 
  - pip install cutadapt 
  - sudo apt-get update -qq
  - sudo apt-get install -qq samtools
  - sudo apt-get install -qq bowtie2
  - sudo apt-get install -qq bedtools
  - wget https://github.com/weizhongli/cdhit/releases/download/V4.6.8/cd-hit-v4.6.8-2017-1208-source.tar.gz
  - tar xvf cd-hit-v4.6.8-2017-1208-source.tar.gz --gunzip
  - cd cd-hit-v4.6.8-2017-1208
  - make
  - cd cd-hit-auxtools
  - make
  - cd ../..
  - python setup.py install
#  - pip install -e .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

#notifications
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
