language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
# command to install dependencies
install:
#travis can is not able to install schema
#  - which python
#  - curl -sSf -o python-2.7.tar.bz2 ${archive_url}
#  - sudo tar xjf python-2.7.tar.bz2 --directory / 
#  - which python
  - wget https://github.com/yhoogstrate/flaimapper/archive/v3.0.0.tar.gz
  - tar xvf v3.0.0.tar.gz --gunzip
  - cd flaimapper-3.0.0
  - cd src
  - sudo pip install .
  - cd ../..
  - rm -r flaimapper-3.0.0
  - pip install schema 
  - pip install cutadapt 
  - sudo apt-get update -qq
  - wget https://github.com/samtools/samtools/releases/download/1.8/samtools-1.8.tar.bz2 -O samtools.tar.bz2
  - tar -xjvf samtools.tar.bz2
  - cd samtools-1.8/
  - make
  - sudo make install
  - cd ..
  - sudo apt-get install -qq bowtie2
  - wget https://github.com/arq5x/bedtools2/releases/download/v2.26.0/bedtools-2.26.0.tar.gz
  - tar -zxvf bedtools-2.26.0.tar.gz
  - cd bedtools2/
  - make
  - sudo make install
  - cd ..
  - pwd
  - samtools view -@ 1 -F 0x10 -Sb /home/travis/build/luidale/starpa/tests/data/trim_output/HLRPI13_pseudoSE.sam > /home/travis/build/luidale/starpa/tests/data/trim_output/HLRPI13_For_unsorted.bam
  - ls -l tests/data/trim_output/
  - samtools sort -o /home/travis/build/luidale/starpa/tests/data/trim_output/HLRPI13_For.bam /home/travis/build/luidale/starpa/tests/data/trim_output/HLRPI13_For_unsorted.bam
  - ls -l tests/data/trim_output/  
  - wget https://github.com/weizhongli/cdhit/releases/download/V4.6.8/cd-hit-v4.6.8-2017-1208-source.tar.gz
  - tar xvf cd-hit-v4.6.8-2017-1208-source.tar.gz --gunzip
  - cd cd-hit-v4.6.8-2017-1208
  - make
  - PATH=$(pwd):$PATH
  - cd cd-hit-auxtools
  - make
  - PATH=$(pwd):$PATH
  - cd ../..
  - python setup.py install
#  - pip install -e .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

#notifications
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
